In [1]:
# imports
import pandas as pd
import numpy as np
import glob
import os
os.chdir("CSV_files/Raw_CSVs")

In [2]:
# Creating a list of file names in the directory
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [3]:
# Merging all CSVs together

# for loop to convert csv column names all to lower case (needed to combine)
csv_list = []

for f in all_filenames:
#     import each csv seperately into a variable
    ea_csv = pd.read_csv(f)
#     remove uppercase letters in column names
    ea_csv.columns = map(str.lower, ea_csv.columns)
#     remove spaces letters in column names
    ea_csv.columns = ea_csv.columns.str.replace(' ', '')
    
    
#     convert birthyear to Int (INT includes NaNs)
    ea_csv['birthyear'] = ea_csv['birthyear'].round(decimals=0).astype('Int64')
    

    
    
#     print(ea_csv)
#     append the csv variable object to csv_list
    csv_list.append(ea_csv)


# print(len(csv_list))

In [4]:
# concat all csv objects into one dataframe variable
master_csv = pd.concat([i for i in csv_list])

# check for null values (possibly need to clean data)
# master_csv.isnull().sum()

master_csv

,tripduration,starttime,stoptime,startstationid,startstationname,startstationlatitude,startstationlongitude,endstationid,endstationname,endstationlatitude,endstationlongitude,bikeid,usertype,birthyear,gender
0,156,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,42293,Subscriber,1996,1
1,143,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44740,Subscriber,1998,1
2,305,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,-74.050389,41369,Subscriber,1988,2
3,1097,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,-74.057271,42285,Customer,2001,1
4,277,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,45231,Subscriber,1965,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53828,270,2020-10-13 15:05:35.0860,2020-10-13 15:10:05.3430,3207,Oakland Ave,40.737604,-74.052478,3640,Journal Square,40.733670,-74.062500,44744,Subscriber,1963,2
53829,400,2020-10-13 15:09:03.4890,2020-10-13 15:15:43.9750,3209,Brunswick St,40.724176,-74.050656,3209,Brunswick St,40.724176,-74.050656,45345,Subscriber,1984,1
53830,206,2020-10-13 15:11:34.3500,2020-10-13 15:15:00.5030,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,47019,Subscriber,1993,1
53831,216,2020-10-13 15:11:49.1510,2020-10-13 15:15:25.6930,3195,Sip Ave,40.730897,-74.063913,3225,Baldwin at Montgomery,40.723659,-74.064194,42191,Subscriber,1966,1
53832,418,2020-10-13 15:12:31.7920,2020-10-13 15:19:30.5280,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,-74.043117,47255,Subscriber,1991,1

## Explore the data

In [ ]:
# master_csv.loc[(master_csv['birthyear']==1970.0) & (master_csv['gender']!=0)]